version: '3.8'

services:
  ticketing-redis:
    image: redis:alpine
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    container_name: ticketing-redis
    ports:
      - "6379:6379"
    networks:
      - ticketing-net

  ticketing-service:
    build: ./ticketing_server
    container_name: ticketing-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=ticketing-redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - CLIENT_KEY=${CLIENT_KEY}
      - TOSS_PAYMENTS_URL=${TOSS_PAYMENTS_URL}
    depends_on:
      - ticketing-redis
    networks:
      - ticketing-net

  payment-service:
    build: ./payment_server
    container_name: payment-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=ticketing-redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - CLIENT_KEY=${CLIENT_KEY}
      - TOSS_PAYMENTS_URL=${TOSS_PAYMENTS_URL}
    depends_on:
      - ticketing-redis
    networks:
      - ticketing-net

networks:
  ticketing-net:
    driver: bridge